// All prompts in both languages
// Bad practice? I can't hear you LALALALALA
window._languageDiff = {
    en: {
        BackPrompt: `Are you sure you want to close the editor? All changes will be lost.`,
        PublishPrompt: `Are you sure you want to publish changes to the page ""?`,
        RedirectMessage: `This page is a <i>redirect</i> to the page "".`,
        ConflictMessage: `This page has been updated during this editing session. Please save all your changes locally and reload the page.`,
        YouNeedToLogin: `You need to log in to be able to edit pages.`,
        DeletionConfirmation: "Are you sure you want to delete this page?",
        DraftDeletion: "Are you sure you want to delete this draft?",
        ImageDeletionConfirmation: "Are you sure you want to delete this image?",
        MovingConfirmation: "Where are you moving this page?",
        AdminLogAppearance: "This action will appear in admin log.",
        ReasonNeeded: "You need a justified reason for deletion:",
        RefTool: "Reference tool",
        RedirectFrom: "Redirected from page",

        ImageTitle: `Images on this page`,
        HistoryTitle: `History of this page`,
        MetadataTitle: `Metadata of this page`,
        BringBackHistoryText: "Reverting page to ver.",
        CreatePageWith: "Create page",
        UserText: "Username",
        ChangeDescText: "Description",
        TimeText: "Date",
        VersionText: "Version",
        LightThemeText: "Light Theme",
        DarkThemeText: "Dark Theme",
        MoveLocation: "New location - Page title",

        BackButton: "Back",
        CancelButton: "Cancel",
        LeaveButton: "Exit",
        PreviewButton: "Preview changes",
        UnpreviewButton: "Hide changes",
        PublishButton: "Publish changes",
        PublishShort: "Publish",
        HistoryButton: "History",
        MoveButton: "Move",
        DeleteButton: "Delete",
        ChangesInfoText: "Changes info",
        ConfirmAddingImageButton: "Confirm image upload",
        AddImageButton: "Upload image",
        DeleteImage: "Remove image",
        LoggedInAs: "Logged in as",

        OpenSourceCode: "Show source code",
        CloseSourceCode: "Hide source code",
        ReturnToOldVer: "Roll back",
        ShowDiff: "Show diff",
        HideDiff: "Hide diff",

        /** Protection levels */
        LowClearanceMessage: "Your account doesn't have sufficient privileges to edit this page.",
        Level0Protection: "No protection",
        Level1Protection: "Basic protection",
        Level2Protection: "Advanced protection",
        Level3Protection: "System protection",

        SystemAdmin: "System Administrator",
        HigherAdmin: "Senior Administrator",
        Admin: "Administrator",
        ApprovedUser: "Verified User",
        User: "User",
        Banned: "Banned"
    },
    rs: {
        BackPrompt: `Da li ste sigurni da želite da izađete iz editora? Sve izmene biće izgubljene.`,
        PublishPrompt: `Da li ste sigurni da želite da objavite ove izmene na stranicu ""?`,
        RedirectMessage: `Ova stranica je <i>redirect</i> do stranice "".`,
        ConflictMessage: "Ova stranica je izmenjena tokom vaše sesije editovanja. Molim vas lokalno sačuvajte sve izmene i osvežite stranicu.",
        YouNeedToLogin: "Morate se ulogovati da bi uređivali stranice.",
        DeletionConfirmation: "Da li ste sigurni da želite da obrišete ovu stranicu?",
        DraftDeletion: "Da li ste sigurni da želite da obrišete ovaj draft?",
        ImageDeletionConfirmation: "Da li ste sigurni da želite da obrišete ovu sliku?",
        MovingConfirmation: "Na koju lokaciju želite da pomerite ovu stranicu?",
        AdminLogAppearance: "Ova akcija će se prikazati u admin log-u.",
        ReasonNeeded: "Potrebno je da imate opravdan razlog za brisanje:",
        RefTool: "Alatka za izvore",
        RedirectFrom: "Redirect sa stranice",

        ImageTitle: `Slike stranice`,
        HistoryTitle: `Istorija stanice`,
        MetadataTitle: `Metapodaci stranice`,
        BringBackHistoryText: "Vraćanje stranice na verziju",
        CreatePageWith: "Stvori stranicu s imenom",
        UserText: "Korisnik",
        ChangeDescText: "Opis izmena",
        TimeText: "Vreme",
        VersionText: "Verzija",
        LightThemeText: "Svetla Tema",
        DarkThemeText: "Tamna Tema",
        MoveLocation: "Nova lokacija - Naslov stranice",

        BackButton: "Nazad",
        CancelButton: "Otkaži",
        LeaveButton: "Izađi",
        PreviewButton: "Prikaži izmene",
        UnpreviewButton: "Sakrij izmene",
        PublishButton: "Objavi izmene",
        PublishShort: "Objavi",
        HistoryButton: "Istorija",
        DeleteButton: "Obriši",
        MoveButton: "Pomeri",
        ChangesInfoText: "Informacije o izmenama",
        ConfirmAddingImageButton: "Potvrdi dodavanje slike",
        AddImageButton: "Dodaj sliku",
        DeleteImage: "Obriši sliku",
        LoggedInAs: "Ulogovani ste kao",

        OpenSourceCode: "Otvori izvorni kod",
        CloseSourceCode: "Zatvori izvorni kod",
        ReturnToOldVer: "Vrati na ovu verziju",
        ShowDiff: "Prikaži diff",
        HideDiff: "Zatvori diff",

        /** Protection levels */
        LowClearanceMessage: "Vaš nalog nema dovoljne privilegije da bi uređivao ovu stranicu.",
        Level0Protection: "Nema zaštite",
        Level1Protection: "Osnovna zaštita",
        Level2Protection: "Napredna zaštita",
        Level3Protection: "Sistemska zaštita",

        SystemAdmin: "Sistemski Administrator",
        HigherAdmin: "Viši Administrator",
        Admin: "Administrator",
        ApprovedUser: "Potvrđeni Korisnik",
        User: "Korisnik",
        Banned: "Banovan"
    }
};